### ISSUE TITLE
STB font renderer Create function signature incorrect

### ISSUE THREAD

**Issue by Coder666** [tesch1/turbobadger#20]
The virtual function `STBFontRenderer::Create` signature does not match that of the virtual function being overridden in the parent class TBFontRenderer and thus does not comple.

Requires `const char* filename` to be replaced with `const TBStr&` and then a modification is also required in the create function to obtain the filename buffer via the `CStr` function

**Comment by tesch1** [comment]
@Coder666 Thanks for the note!

I've just pushed a fix.  Haven't tried the STB renderer for a long time - probably the included stb is also quite out of date - open to patches!
