### ISSUE TITLE
Building on Windows / ConfigureVS2019.bat

### ISSUE THREAD

**Issue by Coder666** [tesch1/turbobadger#21]
Here is the contents of a configure batch file `ConfigureVS2019.bat` I am using on Windows to create the Visual Studio solution files

```
@echo off
@mkdir build-x64
@pushd build-x64
cmake ..\ -DTB_BUILD_DEMO=GLFW -G "Visual Studio 16 2019" -A x64
@popd

@mkdir build-x86
@pushd build-x86
cmake ..\ -DTB_BUILD_DEMO=GLFW -G "Visual Studio 16 2019" -A Win32
@popd
```

Maybe useful to include a variant of this in the source tree.

Cheers

Tom

**Comment by tesch1** [comment]
see https://github.com/tesch1/turbobadger/blob/hastybadger/.github/workflows/cmake.yml
