### ISSUE TITLE
TBProgressSpinner::IsRunning is not const-qualified

### ISSUE THREAD

**Issue by Xeverous** [tesch1/turbobadger#8]
https://github.com/tesch1/turbobadger/blob/123ed5a11f7c583c4342f48744ba081a5d8912ca/src/tb/tb_widgets_common.h#L240-L241

I guess there is nothing behind this, just an oversight.

**Comment by tesch1** [comment]
Yeah, a lot of the original turbobadger was missing these, I've cleaned up a bunch, but certainly I missed some.  PRs welcome.
